version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks: 
      - app-net
    restart: always
  
  crawler:
    
